### PR TITLE
Add Honeybadger class dependecy injection

### PR DESCRIPTION
**Pull request by jeniaefimov**

### CODE REVIEW

**Comment by jeniaefimov** [comment]
@flyerhzm please check this idea

**Comment by jeniaefimov** [comment]
@flyerhzm thanks for merge this one. Is it possible to release new version of gem?
Thanks again.

**Comment by flyerhzm** [comment]
@jeniaefimov I just released 1.13.0, thanks for your contribution.

**Comment by jeniaefimov** [comment]
@flyerhzm thank you!

**Pull request merged**
